default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hamzis_systems_development
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

test:
  adapter: postgresql
  encoding: unicode
  database: hamzis_systems_test
  username: postgres
  password: 1234
  host: localhost
  port: 5432


production:
  primary: &primary_production
    <<: *default
    database: hamzis_systems_production
    username: hamzis_systems
    password: <%= ENV["HAMZIS_SYSTEMS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: hamzis_systems_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: hamzis_systems_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: hamzis_systems_production_cable
    migrations_paths: db/cable_migrate
