default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  # Change the database name to be generic
  database: construction_erp_development
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  host: <%= ENV.fetch("PGHOST", "localhost") %>

test:
  <<: *default # Use the default anchor to keep it clean
  database: construction_erp_test
  username: <%= ENV.fetch("POSTGRES_USER", "postgres") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  host: localhost
  port: 5432

staging:
  primary: &primary_staging
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *primary_staging
    database: erp_staging_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    # Use an ENV variable for the DB name so you don't have to edit code for new clients
    database: <%= ENV.fetch("PRODUCTION_DB_NAME", "erp_production") %>
    username: <%= ENV.fetch("PRODUCTION_DB_USER", "erp_admin") %>
    password: <%= ENV["ERP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: erp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: erp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: erp_production_cable
    migrations_paths: db/cable_migrate
